format_version: 10
pipelines:
  master-ami:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/raju-b71/master-ami.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:hDEVaGzCtlYK3Cwott/s/Q==:3t0AarZ1uJhV05MPg/k/imWXwLPkSs1ymgynrLX+ESU=
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
              - exec: { command: terraform, arguments: [ "init"], run_if: passed }
              - exec: { command: terraform, arguments: [ "apply", "-auto-approve" ], run_if: passed }
               #  s